server:
  port: 8190
  servlet:
    context-path: /lesson6-cart

integrations:
  product-service:
    url: http://localhost:8189/lesson6-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000